apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: musicxshare
  name: musicxshare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: musicxshare
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: musicxshare
    spec:
      containers:
      - image: 365591124323.dkr.ecr.us-east-1.amazonaws.com/jayanthroyg/new-ecr-musicxshare:v1.1.12
        name: musicshare
        resources: {}
status: {}
