version: 0.2

phases:
 pre_build:
 commands:
  - echo Started Pre Build Steps....
  - CONTAINER_NAME=$(aws ssm get-parameter --name "/spring-boot-app/eks-deploy/container-name" --with-decryption --query "Parameter.Value" --output text)
  - DEPLOYMENT_NAME=$(aws ssm get-parameter --name "/spring-boot-app/eks-deploy/deploy-name" --with-decryption --query "Parameter.Value" --output text)
  - echo Fetching ECR registry URI from Parameter Store...
  - ECR_URI=$(aws ssm get-parameter --name "/spring-boot-app/docker_ecr_repo/uri" --with-decryption --query "Parameter.Value" --output text)
  - echo Extracting AWS region from ECR URI...
  - REGION=$(echo $ECR_URI | cut -d'.' -f4)
  - echo Logging in to Amazon ECR...
  - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_URI
  - echo Updating kubeconfig for EKS...
  - aws eks update-kubeconfig --region $REGION --name eks-cluster-1

 build:
 commands:
  - echo Building the JAR file...
  - mvn clean install -B -q
  - echo Building Docker image...
  - docker build -t $ECR_URI:v1.$CODEBUILD_BUILD_NUMBER .
  - echo Pushing Docker image to ECR...
  - docker push $ECR_URI:v1.$CODEBUILD_BUILD_NUMBER

 post_build:
 commands:
  - echo Updating Kubernetes deployment in EKS...
  - kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=$ECR_URI:v1.$CODEBUILD_BUILD_NUMBER

artifacts:
	files:
	- spring-deploy.yaml







version: 0.2

phases:
 pre_build:
  commands:
   - echo Started Pre Build Steps....
   - CONTAINER_NAME="spring-boot-app"
   - echo Fetching ECR registry URI from Parameter Store...
   - ECR_URI=$(aws ssm get-parameter --name "/spring-boot-app/docker_ecr_repo/uri" --with-decryption --query "Parameter.Value" --output text)
   - echo Extracting AWS region from ECR URI...
   - REGION=$(echo $ECR_URI | cut -d'.' -f4)
   - echo Logging in to Amazon ECR...
   - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_URI
   - echo Updating kubeconfig for EKS...
   - aws eks update-kubeconfig --region $REGION --name your-eks-cluster-name

 build:
  commands:
   - echo Building the JAR file...
   - mvn clean install
   - echo Building Docker image...
   - docker build -t $ECR_URI:v1.$CODEBUILD_BUILD_NUMBER .

 post_build:
  commands:
   - echo Pushing Docker image to ECR...
   - docker push $ECR_URI:v1.$CODEBUILD_BUILD_NUMBER
   - echo Updating Kubernetes deployment in EKS...
   - kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=$ECR_URI:v1.$CODEBUILD_BUILD_NUMBER
